name: Github Actions 실행시켜보기

on:
  push:
    branches:
      - main

# Workflow는 여러개의 job으로 이루어져있고
jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest
#하나의 Job은 여러개의 Step으로 이루어져있다.
    steps:
      - name: Hello World 출력하기
        run: echo "hello World"
